# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(425, 301)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kmmile_layout = QtWidgets.QHBoxLayout()
        self.kmmile_layout.setObjectName("kmmile_layout")
        self.kmmile_km = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.kmmile_km.setObjectName("kmmile_km")
        self.kmmile_layout.addWidget(self.kmmile_km)
        self.kmmile_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.kmmile_label.setObjectName("kmmile_label")
        self.kmmile_layout.addWidget(self.kmmile_label)
        self.kmmile_mile = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.kmmile_mile.setObjectName("kmmile_mile")
        self.kmmile_layout.addWidget(self.kmmile_mile)
        self.verticalLayout.addLayout(self.kmmile_layout)
        self.inchcm_layout = QtWidgets.QHBoxLayout()
        self.inchcm_layout.setObjectName("inchcm_layout")
        self.inchcm_inch = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.inchcm_inch.setObjectName("inchcm_inch")
        self.inchcm_layout.addWidget(self.inchcm_inch)
        self.inchcm_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.inchcm_label.setObjectName("inchcm_label")
        self.inchcm_layout.addWidget(self.inchcm_label)
        self.inchcm_cm = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.inchcm_cm.setObjectName("inchcm_cm")
        self.inchcm_layout.addWidget(self.inchcm_cm)
        self.verticalLayout.addLayout(self.inchcm_layout)
        self.fc_layout = QtWidgets.QHBoxLayout()
        self.fc_layout.setObjectName("fc_layout")
        self.fc_f = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.fc_f.setObjectName("fc_f")
        self.fc_layout.addWidget(self.fc_f)
        self.fc_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.fc_label.setObjectName("fc_label")
        self.fc_layout.addWidget(self.fc_label)
        self.fc_c = QtWidgets.QSpinBox(parent=self.verticalLayoutWidget)
        self.fc_c.setObjectName("fc_c")
        self.fc_layout.addWidget(self.fc_c)
        self.verticalLayout.addLayout(self.fc_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.kmmile_label.setText(_translate("Dialog", "km/mile"))
        self.inchcm_label.setText(_translate("Dialog", "inch/cm"))
        self.fc_label.setText(_translate("Dialog", "F/C"))
